config/routes.rb
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2010-2019 RedmineUP
# http://www.redmineup.com/
#
# redmine_contacts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_contacts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_contacts.  If not, see <http://www.gnu.org/licenses/>.

#custom routes for this plugin
  resources :contacts, :path_names => {:contacts_notes => 'notes'} do
    collection do
      get :bulk_edit, :context_menu, :edit_mails, :contacts_notes
      post :bulk_edit, :bulk_update, :send_mails, :preview_email
      delete :bulk_destroy
    end
    member do
      get 'tabs/:tab' => 'contacts#show', :as => "tabs"
      get 'load_tab' => 'contacts#load_tab', :as => "load_tab"
    end
    resources :contacts_projects, :path => "projects", :only => [:new, :create, :destroy]
  end

  resources :projects do
    resources :contacts, :path_names => {:contacts_notes => 'notes'} do
      collection do
        get :contacts_notes
      end
    end
    resources :contact_imports, :only => [:new, :create, :show] do
      member do
        get :settings
        post :settings
        get :mapping
        post :mapping
        get :run
        post :run
      end
    end
    resources :deal_imports, :only => [:new, :create, :show] do
      member do
        get :settings
        post :settings
        get :mapping
        post :mapping
        get :run
        post :run
      end
    end
    resources :deal_categories

  end
  resources :deals do
    collection do
      get :bulk_edit
      get :context_menu
      get :edit_mails
      get :preview_email
      post :bulk_edit, :bulk_update, :send_mails, :update_form
      put :update_form
      delete :bulk_destroy
    end
  end

  resources :projects do
    resources :deals, :only => [:new, :create, :index]
    resources :deal_categories, :only => [:new, :create, :index]
  end

  resources :deal_categories, :only => [:edit, :update, :destroy]

  resources :deal_statuses, :except => :show do
    collection do
      put :assign_to_project
    end
  end

  resources :projects do
    resources :crm_queries, :only => [:new, :create]
  end

  resources :crm_queries, :except => [:show]

  resources :notes

  match '/contacts_tags', :controller => 'contacts_tags', :action => 'destroy', :via => :delete

  resources :contacts_tags do
    collection do
      post :merge, :context_menucha
      get :context_menu, :merge
    end
  end

  match 'projects/:project_id/contacts/:contact_id/new_task' => 'contacts_issues#new', :via => :post

  match 'contacts/:contact_id/duplicates' => 'contacts_duplicates#index', :via => [:get, :post]

  match 'projects/:project_id/deal_categories/new' => 'deal_categories#new', :via => [:get, :post]


  match 'auto_completes/taggable_tags' => 'auto_completes#taggable_tags', :via => :get, :as => 'auto_complete_taggable_tags'
  match 'auto_completes/contact_tags' => 'auto_completes#contact_tags', :via => :get, :as => 'auto_complete_contact_tags'
  match 'auto_completes/contacts' => 'auto_completes#contacts', :via => :get, :as => 'auto_complete_contacts'
  match 'auto_completes/companies' => 'auto_completes#companies', :via => :get, :as => 'auto_complete_companies'
  match 'auto_completes/deals' => 'auto_completes#deals', :via => :get, :as => 'auto_complete_deals'

  match 'users/new_from_contact/:id' => 'users#new_from_contact', :via => :get
  match 'contacts_duplicates/:action' => 'contacts_duplicates', :via => [:get, :post]
  match 'contacts_duplicates/search' => 'contacts_duplicates#search', :via => :get, :as => 'contacts_duplicates_search'
  match 'contacts_issues/:action' => 'contacts_issues', :via => [:get, :post, :delete, :put]
  match 'contacts_vcf/:action' => 'contacts_vcf', :via => [:get, :post]
  match 'deal_contacts/:action' => 'deal_contacts', :via => [:get, :post, :delete]
  match 'deals_tasks/:action' => 'deals_tasks', :via => [:get, :post, :put]
  match 'contacts_settings/:action' => 'contacts_settings', :via => [:get, :post]
  match 'contacts_mailer/:action' => 'contacts_mailer', :via => [:get, :post]
  match 'attachments/contacts_thumbnail/:id(/:size)', :controller => 'attachments', :action => 'contacts_thumbnail', :id => /\d+/, :via => :get

app/helpers/deals_helper.rb
# encoding: utf-8
#
# This file is a part of Redmine CRM (redmine_contacts) plugin,
# customer relationship management plugin for Redmine
#
# Copyright (C) 2010-2025 RedmineUP
# http://www.redmineup.com/
#
# redmine_contacts is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# redmine_contacts is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with redmine_contacts.  If not, see <http://www.gnu.org/licenses/>.

module DealsHelper
  include ContactsHelper
  def collection_for_status_select
    deal_statuses.collect{|s| [s.name, s.id.to_s]}
  end

  def deal_status_options_for_select(select="")
     options_for_select(collection_for_status_select, select)
  end

  def deal_statuses
    (!@project.blank? ? @project.deal_statuses : DealStatus.order("#{DealStatus.table_name}.status_type, #{DealStatus.table_name}.position")) || []
  end

  def deal_status_url(status_id, options={})
    {:controller => 'deals',
     :action => 'index',
     :set_filter => 1,
     :project_id => @project,
     :fields => [:status_id],
     :values => {:status_id => [status_id]},
     :operators => {:status_id => '='}}.merge(options)
  end

  def pipeline_status_tag(deal_status, count, index)
    total = @processor.scope.count
    width ||= 20 if deal_status.is_won?
    width ||= 40 if deal_status.is_lost?
    width ||= (100 - 20) * (count.to_f / total.to_f) + 20
    width_style = index == 0 ? "" : "width: #{width}%"
    status_tag = content_tag(:span, deal_status.name)
    content_tag(:span, status_tag, :class => "tag-label-color", :style => "background-color:#{deal_status.color_name};color:white; #{width_style}")
  end

  def remove_contractor_link(contact)
    link_to(image_tag('delete.png'),
      {:controller => "deal_contacts", :action => 'delete', :project_id => @project, :deal_id => @deal, :contact_id => contact},
      :remote => true,
      :method => :delete,
      :data => {:confirm => l(:text_are_you_sure)},
      :class  => "delete", :title => l(:button_delete)) if  User.current.allowed_to?(:edit_deals, @project)
  end

  def link_to_deal(deal)
    link_to deal.name, deal_path(deal)
  end

  def deal_list_styles_for_select
    [[l(:label_crm_list_excerpt), "list_excerpt"],
     [l(:label_crm_list_list), "list"],
     [l(:label_crm_list_board), "list_board"],
     [l(:label_calendar), "crm_calendars/crm_calendar"],
     [l(:label_crm_pipeline), "list_pipeline"]]
  end

  def deals_list_style
    list_styles = deal_list_styles_for_select.map(&:last)
    if params[:deals_list_style].blank?
      list_style = list_styles.include?(session[:deals_list_style]) ? session[:deals_list_style] : RedmineContacts.default_list_style.gsub("list_cards", "list_board")
    else
      list_style = list_styles.include?(params[:deals_list_style]) ? params[:deals_list_style] : RedmineContacts.default_list_style.gsub("list_cards", "list_board")
    end
    session[:deals_list_style] = list_style
  end

  def retrieve_deals_query
    if params[:status_id] || !params[:period].blank? || !params[:category_id].blank? || !params[:assigned_to_id].blank?
      session[:deals_query] = {:project_id => (@project ? @project.id : nil),
                               :status_id => params[:status_id],
                               :category_id => params[:category_id],
                               :period => params[:period],
                               :assigned_to_id => params[:assigned_to_id]}
    else
      if api_request? || params[:set_filter] || session[:deals_query].nil? || session[:deals_query][:project_id] != (@project ? @project.id : nil)
        session[:deals_query] = {}
      else
        params.merge!(session[:deals_query])
      end
    end
  end

  def pipeline_prices(scope)
    prices_collection_by_currency(scope.group_by(&:currency).map{|k,v| [k, v.inject(0) { |sum, x| sum + x.price.to_f } ] }).join(' / ').html_safe
  end

  def deals_to_csv(deals)
    return "" unless User.current.allowed_to?(:export_contacts, @project, :global => true)
    decimal_separator = l(:general_csv_decimal_separator)
    encoding = 'utf-8'
    export = FCSV.generate(:col_sep => l(:general_csv_separator)) do |csv|
      # csv header fields
      headers = [ "#",
                  l(:field_name, :locale => :en),
                  l(:field_background, :locale => :en),
                  l(:field_currency, :locale => :en),
                  l(:field_price, :locale => :en),
                  l(:label_crm_probability, :locale => :en),
                  l(:label_crm_expected_revenue, :locale => :en),
                  l(:field_due_date, :locale => :en),
                  l(:field_author, :locale => :en),
                  l(:field_assigned_to, :locale => :en),
                  l(:field_status, :locale => :en),
                  l(:field_contact, :locale => :en),
                  l(:field_category, :locale => :en),
                  l(:field_created_on, :locale => :en),
                  l(:field_updated_on, :locale => :en)
                  ]

      custom_fields = DealCustomField.order(:name)
      custom_fields.each {|f| headers << f.name}
      csv << headers.collect {|c| Redmine::CodesetUtil.from_utf8(c.to_s, encoding) }
      # csv lines
      deals.each do |deal|
        fields = [deal.id,
                  deal.name,
                  deal.background,
                  deal.currency,
                  deal.price,
                  deal.probability,
                  deal.expected_revenue,
                  format_date(deal.due_date),
                  deal.author,
                  deal.assigned_to,
                  deal.status,
                  deal.contact,
                  deal.category,
                  format_date(deal.created_on),
                  format_date(deal.updated_on)
                  ]
        deal.custom_field_values.sort_by{|v| v.custom_field.name}.each {|custom_value| fields << RedmineContacts::CSVUtils.csv_custom_value(custom_value) }
        csv << fields.collect {|c| Redmine::CodesetUtil.from_utf8(c.to_s, encoding) }
      end
    end
    export
  end

  def importer_link
    project_deal_imports_path
  end

  def importer_show_link(importer, project)
    project_deal_import_path(:id => importer, :project_id => project)
  end

  def importer_settings_link(importer, project)
    settings_project_deal_import_path(:id => importer, :project => project)
  end

  def importer_run_link(importer, project)
    run_project_deal_import_path(:id => importer, :project_id => project, :format => 'js')
  end

  def importer_link_to_object(deal)
    link_to deal.name, deal_path(deal)
  end

  def _project_deals_path(project, *args)
    if project
      project_deals_path(project, *args)
    else
      deals_path(*args)
    end
  end
end

app/views/deals/_attributes.html.erb
<% if @deal.custom_field_values.any? %>
<div id="attributes">

	<h3><%= l(:label_deal) %></h3>
	<table class="attributes">
		<% @deal.custom_field_values.each do |custom_value| %>
			<% if !custom_value.value.blank? %>
			<tr> <th class = "custom_field"><%= custom_value.custom_field.name %>:</th><td> <%=h show_value(custom_value) %></td> </tr>
			<% end %>
		<% end %>
	</table>

</div>
<% end %>

app/views/deals/_board_deals_counts.html.erb
<tr>
  <% deal_statuses.each do |deal_status| %>
    <th style="width: <%= 100/deal_statuses.size %>%;">
      <%= "#{deal_status.name} (#{@deals_scope.where(:status_id => deal_status.id).count})"%>
    </th>
  <% end %>
</tr>

app/views/deals/_custom_field_form.html.erb
<p><%= form.check_box :is_filter %></p>
<p><%= form.check_box :visible, :label => l(:label_crm_contacts_show_in_list) %></p>
<% if (@custom_field.respond_to?(:format) && @custom_field.format.searchable_supported) || !@custom_field.respond_to?(:format) %>
<p><%= form.check_box :searchable %></p>
<% end %>

app/views/deals/_deals_statistics.html.erb
<% if deal_statuses.any? %>
	<div id="deals_statistics">
		<div class="contextual">
			<%= link_to l(:label_crm_sales_funnel), {:controller => 'deals', :action => 'index', :project_id => @project, :deals_list_style => 'list_pipeline'} %>
		</div>
		<h3><%= l(:label_crm_statistics) %></h3>
		<table class="deals_statistics">
			<% deal_statuses.each do |deal_status| %>
			<tr>
				<td>
					<span class="tag-label-color" style=<%= "background-color:#{deal_status.color_name};color:white;" %> >
						<%= link_to "#{deal_status.name}(#{@project ? @project.deals.visible.with_status(deal_status.id).count : Deal.visible.with_status(deal_status.id).count})".html_safe, deal_status_url(deal_status.id, :project_id => @project) %>
					</span>
				</td>
				<td>
					<strong>
						<%= prices_collection_by_currency(Deal.by_project(@project).visible.where(:status_id => deal_status.id).group(:currency).sum(:price), :hide_zeros => true).join(' / ').html_safe %>
					</strong>
				</td>
			</tr>
			<% end %>
		</table>
	</div>
<% end %>

app/views/deals/_line_fields.html.erb
<% product = f.object.product %>
<tr class="line fields sortable-line" id="line-<%= f.object.id %>" >
  <% unless product.blank? %>
    <td class="product-image"><%= product_tag(product, :size => 32, :type => 'image')  %></td>
  <% end %>
  <td class="item" colspan="<%= product.blank? ? 2 : 1 %>">
    <%= product_tag(product, :type => 'plain') unless product.blank? %>
    <%= f.hidden_field :product_id %>
    <% if !product.blank? && f.object.description.blank? %>
      <br>
      <em class="info"><%= link_to_function "(#{l(:label_products_add_description)})", "$(this).hide(); $(this).parent().next().show(); return false;"  %></em>
    <% end %>
    <%= f.text_area :description, :no_label => true, :rows => f.object.description.blank? ? 2 : [f.object.description.lines.count, 2].max, :onkeyup => "activateTextAreaResize(this);", :style => "width:99%; #{(product.blank? || !f.object.description.blank?) ? "" : "display:none;"}" -%>
  </td>
  <% f.object.custom_field_values.each do |cf| %>
    <td><%= custom_field_tag("deal[lines_attributes][#{f.index}]", cf) %></td>
  <% end %>
  <td class="quantity"><%= f.text_field :quantity, :no_label => true, :size => 6, :onkeyup => 'updateTotal(this)' %></td>
  <td class="price"><%= f.text_field :price, :no_label => true, :size => 8, :onkeyup => 'updateTotal(this)' %></td>

  <% if !ContactsSetting.disable_taxes? || (f.object.container.respond_to?(:has_taxes?) && f.object.container.has_taxes?)  %>
  <td class="tax">
    <% line_tax = (f.object.new_record? && f.object.tax.blank?) ? ContactsSetting.default_tax : f.object.tax %>
    <%= check_box_tag :show_tax, "1", false, :onclick=>"$(this).hide(); $(this).parent().find('.tax-fields').show(); $(this).next().find('input').focus(); return false;" if line_tax.blank? || line_tax == 0 %>
    <span class="tax-fields" style="white-space: nowrap; <%= line_tax.blank? || line_tax == 0 ? "display:none;" : "" %>"><%= f.text_field :tax, :no_label => true, :size => 5, :value => line_tax %>&nbsp;%
    </span>
  </td>
  <% end %>
  <td class="discount">
    <%= check_box_tag :show_discount, "1", false, :onclick=>"$(this).hide(); $(this).parent().find('.discount-fields').show(); $(this).next().find('input').focus(); return false;" if f.object.discount.to_i == 0 %>
    <span class="discount-fields" style="white-space: nowrap; <%= f.object.discount.to_i == 0 ? "display:none;" : "" %>">
      <%= f.text_field :discount, :no_label => true, :size => 5, :style => f.object.discount.to_i == 0 ? "display:none;" : "", :onkeyup => 'updateTotal(this)', :class => "discount-fields" %>&nbsp;%
    </span>
  </td>

  <td class="total"><%= format("%.2f\n", f.object.total) if f.object.price && f.object.quantity  %></td>
  <td>
    <%= deals_link_to_remove_fields "", f, :class => "icon icon-del"  %>
  </td>
  <%= f.hidden_field :position, :class => 'position' %>
</tr>

<script type="text/javascript">
  tooglePriceField();
</script>

app/views/deals/_list.html.erb
<%= form_tag({}, :data => {:cm_url => context_menu_deals_path}) do -%>
<%= hidden_field_tag 'back_url', url_for(params.respond_to?(:to_unsafe_hash) ? params.to_unsafe_hash : params), :id => nil %>
<div class="autoscroll">
<table class="list deals issues contacts">
  <thead>
    <tr>
      <th class="checkbox hide-when-print">
        <%= link_to image_tag('toggle_check.png'), {},
                              :onclick => 'toggleCRMIssuesSelection(this); return false;',
                              :title => "#{l(:button_check_all)}/#{l(:button_uncheck_all)}" %>
      </th>
      <%= sort_header_tag('id', :caption => '#', :default_order => 'desc') %>
      <% @query.inline_columns.each do |column| %>
        <%= Redmine::VERSION.to_s >= '3.4' || RedmineContacts.unstable_branch? ? column_header(@query, column) : column_header(column) %>
      <% end %>
    </tr>
  </thead>
  <% previous_group = false %>
  <tbody>
  <% @deals.each do |deal| -%>
  <% if @query.grouped? && (group = @query.group_by_column.value(deal)) != previous_group %>
    <% reset_cycle %>
    <tr class="group open">
      <td colspan="<%= @query.inline_columns.size + 2 %>">
        <span class="expander" onclick="toggleRowGroup(this);">&nbsp;</span>
        <%= group.blank? ? l(:label_none) : column_content(@query.group_by_column, deal) %> <span class="count"><%= @deal_count_by_group[group] %></span>
        <%= link_to_function("#{l(:button_collapse_all)}/#{l(:button_expand_all)}",
                             "toggleAllRowGroups(this)", :class => 'toggle-all') %>
      </td>
    </tr>
    <% previous_group = group %>
  <% end %>
  <tr id="deal-<%= deal.id %>" class="hascontextmenu <%= cycle('odd', 'even') %>">
    <td class="checkbox hide-when-print"><%= check_box_tag("ids[]", deal.id, false, :id => nil) %></td>
    <td class="id"><%= link_to deal.id, deal_path(deal) %></td>
    <%= raw @query.inline_columns.map {|column| "<td class=\"#{column.css_classes}\">#{column_content(column, deal)}</td>"}.join %>
  </tr>
  <% @query.block_columns.each do |column|
       if (text = column_content(column, deal)) && text.present? -%>
  <tr class="<%= current_cycle %>">
    <td colspan="<%= @query.inline_columns.size + 1 %>" class="<%= column.css_classes %>"><%= text %></td>
  </tr>
  <% end -%>
  <% end -%>
  <% end -%>
      <tr class="total">
        <th colspan="<%= @query.inline_columns.size + 2 %>">
          <table class="contacts deals index total">
            <tbody>
            <tr class="total">
              <% if @deal_weighted_amount.map{|k, v| v.to_i > 0}.any? %>
              <th class="title"><%= l(:label_crm_expected_revenue) %>:</th>
              <th class="sum deals-sum">
                <%= prices_collection_by_currency(@deal_weighted_amount, :hide_zeros => true).join('<br/>').html_safe %>
              </th>
              <% end %>
              <th class="title"><%= "#{l(:label_total)} (#{@deals_count}):" %></th>
              <th class="sum deals-sum">
                <%= prices_collection_by_currency(@deal_amount, :hide_zeros => true).join('<br/>').html_safe %>
              </th>
            </tr>

            </tbody>
          </table>

        </th>
      </tr>
  </tbody>
</table>
</div>
<% end -%>

app/views/deals/index.html.erb
<% filtered_params = params.respond_to?(:to_unsafe_hash) ? params.to_unsafe_hash : params %>
<div class="contextual">
  <%= link_to l(:label_crm_deal_new), {:controller => 'deals', :action => 'new', :project_id => @project || Deal.allowed_target_projects.first }, :class => 'icon icon-add' if User.current.allowed_to?(:add_deals, @project, {:global => true}) && Deal.allowed_target_projects.any? %>
  <%= link_to_if_authorized l(:label_crm_import), {:controller => 'deal_imports', :action => 'new', :project_id => @project}, :class => 'icon icon-import', :id => 'import_from_csv' %>
</div>

<% html_title(@query.new_record? ? l(:label_deal_plural) : @query.name) %>

<%= form_tag({ :controller => 'deals', :action => 'index', :project_id => @project }, :method => :get, :id => 'query_form') do %>

    <script type="text/javascript">
       jQuery(function($) {
          // when the #search field changes
          $("#search").observe_field(2, function() {
            var form = $("#query_form"); // grab the form wrapping the search bar.
            var url = form.attr("action");
            form.find('[name="c[]"] option').each(function(i, elem){
              $(elem).attr('selected', true);
              $(elem).prop('selected', true)
            });

            var formData = form.serialize();
            form.find('[name="c[]"] option').each(function(i, elem){
              $(elem).attr('selected', false);
              $(elem).prop('selected', false)
            });

            $.get(url, formData, function(data) { // perform an AJAX get, the trailing function is what happens on successful get.
                $("#contact_list").html(data); // replace the "results" div with the result of action taken
            });
          });
        });
    </script>

    <h2 class="contacts_header">
        <span id='scope_header' class="scope_title">
        <%= @query.new_record? ? l(:label_deal_plural) : h(@query.name)  %>
        </span>

        <span class="live_search">
            <%= text_field_tag(:search, params[:search], :autocomplete => "off", :class => "live_search_field", :placeholder => l(:label_crm_contact_search) ) %>

        </span>

    </h2>
<%= hidden_field_tag 'set_filter', '1' %>
<%= hidden_field_tag 'object_type', 'deal' %>
<div id="query_form_with_buttons" class="hide-when-print">
  <div id="query_form_content">
  <fieldset id="filters" class="collapsible <%= @query.new_record? ? "" : "collapsed" %>">
    <legend onclick="toggleFieldset(this);" class="icon icon-expended"><%= l(:label_filter_plural) %></legend>
    <div style="<%= @query.new_record? ? "" : "display: none;" %>">
      <%= render :partial => 'queries/filters', :locals => {:query => @query} %>
    </div>
  </fieldset>
  <fieldset id="options" class="collapsible collapsed">
    <legend onclick="toggleFieldset(this);" class="icon icon-expended"><%= l(:label_options) %></legend>
    <div style="display: none;">
      <table>
        <tr style="<%= 'display: none;' if deals_list_style != 'list' %>">
          <td><%= l(:field_column_names) %></td>
          <td><%= render_query_columns_selection(@query) %></td>
        </tr>
        <tr>
        <% if ['list', 'list_excerpt'].include?(deals_list_style) %>
            <td><label for='group_by'><%= l(:field_group_by) %></label></td>
            <td><%= select_tag('group_by',
                               options_for_select(
                                 [[]] + @query.groupable_columns.collect {|c| [c.caption, c.name.to_s]},
                                 @query.group_by)
                       ) %></td>
        <% end %>
        <% if deals_list_style == 'list_excerpt' %>
            <td><label for='sort'><%= l(:label_sort) %></label></td>
            <td><%= select_tag('sort',
                               options_for_select(
                                 [[]] +
                                 [[l(:field_contact_status), "status:asc"],
                                  [l(:field_due_date), "due_date:asc"],
                                  [l(:field_created_on), "created_on:desc"],
                                  [l(:field_updated_on), "updated_on:desc"]],
                                 params[:sort] || @query.sort_criteria.try(:first).try(:join, ':'))
                       ) %></td>
        <% end %>

        </tr>
        <%= call_hook(:view_deals_index_query_options, :deals => @deals, :query => @query) %>
        <tr>
          <td><label for='deals_list_style'><%= l(:label_crm_list_partial_style) %></label></td>
          <td><%= select_tag('deals_list_style', options_for_select(deal_list_styles_for_select, deals_list_style)) %></td>
        </tr>
      </table>
    </div>
  </fieldset>
</div>

<%= render :partial => "crm_calendars/buttons" if deals_list_style == 'crm_calendars/crm_calendar' %>

<p class="buttons hide-when-print">
  <%= link_to_function l(:button_apply), 'submit_query_form("query_form")', :class => 'icon icon-checked' %>
  <%= link_to l(:button_clear), { :set_filter => 1, :project_id => @project }, :class => 'icon icon-reload'  %>
  <% if @query.new_record? %>
    <% if User.current.allowed_to?(:save_contacts_queries, @project, :global => true) %>
      <%= link_to_function l(:button_save),
                           "$('#query_form').attr('action', '#{ @project ? new_project_crm_query_path(@project) : new_crm_query_path }'); submit_query_form('query_form')",
                           :class => 'icon icon-save' %>
    <% end %>
  <% else %>
    <% if @query.editable_by?(User.current) %>
      <%= link_to l(:button_contacts_edit_query), edit_crm_query_path(@query, :object_type => "deal"), :class => 'icon icon-edit' %>
      <%= link_to l(:button_contacts_delete_query), crm_query_path(@query, :object_type => "deal"), :data => {:confirm => l(:text_are_you_sure)}, :method => :delete, :class => 'icon icon-del' %>
    <% end %>
  <% end %>
</p>
</div>
<% end %>

<%= error_messages_for 'query' %>
<% if @query.valid? %>
  <div id="contact_list" class="deal_list">
  <% if @deals.empty? %>
    <p class="nodata"><%= l(:label_no_data) %></p>
  <% else %>
    <%= render :partial => deals_list_style %>
    <span class="pagination"><%= pagination_links_full @deals_pages, @deals_count %></span>
  <% end %>
  </div>

  <% other_formats_links do |f| %>
      <%= f.link_to 'CSV', :url => filtered_params %>
  <% end if User.current.allowed_to?(:export_contacts, @project, :global => true) %>
<% end %>

<% if Redmine::VERSION.to_s >= '3.4' || RedmineContacts.unstable_branch? %>
  <%= context_menu %>
<% else %>
  <%= context_menu url_for( {:controller => "deals", :action => "context_menu"} ) %>
<% end %>

<% content_for :sidebar do %>
  <%= call_hook(:view_deals_sidebar_top, :deals => @deals) %>
  <%= render :partial => 'deals_statistics' %>
  <%= render_sidebar_crm_queries('deal') %>
  <%= call_hook(:view_deals_sidebar_after_statistics, :deals => @deals) %>
  <%= render :partial => 'notes/last_notes', :object => @last_notes %>
  <%= call_hook(:view_deals_sidebar_bottom, :deals => @deals) %>
<% end unless (deals_list_style == 'list_board') %>


<% content_for(:header_tags) do %>
  <%= javascript_include_tag :contacts, :plugin => 'redmine_contacts'  %>
  <meta name = "format-detection" content = "telephone=no">
<% end %>

app/views/deals/update_total.js.erb
$('.total').html('<%= escape_javascript(render :partial => 'board_total') %>');
$('.deals_counts').html('<%= escape_javascript(render :partial => 'board_deals_counts') %>');